# https://github.com/caarlos0-graveyard/shell-ci-build
# https://github.com/kward/shunit2/blob/master/.travis.yml
language: shell

addons:
  homebrew:
    packages:
    - coreutils
    - gnu-sed

# The Ubuntu Linux Build Environments
#   https://docs.travis-ci.com/user/reference/linux/
# The macOS Build Environment
#   https://docs.travis-ci.com/user/reference/osx/
# Installing Dependencies
#   https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos
jobs:
  include:
    - os: osx
      osx_image: xcode12.5
    - os: linux
      dist: precise
    - os: linux
      dist: xenial
    - os: linux
      dist: focal

env:
  # Is it possible to `brew install` without updating? · Issue #1670 · Homebrew/brew
  #   https://github.com/Homebrew/brew/issues/1670
  # python - How to not update homebrew automatically when brew install some packages? - Stack Overflow
  #   https://stackoverflow.com/questions/41530314
  - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_AUTO_UPDATING=0 HOMEBREW_UPDATE_PREINSTALL=0 HOMEBREW_NO_ANALYTICS=1
script:
  - test-cases/integration-test.sh

after_script:
  - git status --ignored
